# This is a basic workflow to help you get started with Actions

name: vue-CI

# Controls when the workflow will run
on: ["push", "pull_request"]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run clone
        uses: actions/checkout@v3

      - name: log branch_name
        run: echo $GITHUB_REF

      # - name: Set up docker git
      #   uses: docker/setup-qemu-action@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      
      # - name: setup node
      #   uses: actions/setup-node@v2-beta
      #   with: 
      #       node-version: '14.17'
      #       cache: "yarn"

      # # Runs a single command using the runners shell
      # - name: yarn install
      #   run: yarn install
      
      # - name: build
      #   run: yarn build

      # # Runs a set of commands using the runners shell
      # - name: log file
      #   run: tree ./dist

      - name: Extract branch name
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/}  | awk -F '/' '{print $NF}')"
        #      echo “##[set-output name=commit;]$(echo "555555")”
        run: |
          echo ::set-output name=pr_title::"[Test] Add report file $(date +%d-%m-%Y)"
        id: extract_branch

      - name: Push to ECR
        run: echo ${{ steps.extract_branch.outputs.branch }}

      # - name: docker build
      #   run: docker build . -t 
